blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/YamiCueto/case-algorithms/discussions
    about: "¿Tienes una pregunta sobre el diseño de un algoritmo o dudas pedagógicas? Inicia una discusión en lugar de abrir una Issue."
